#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - curl
  - wget
  - unzip

runcmd:
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker azureuser
  - mkdir -p /opt/opswat
  - cd /opt/opswat
  - |
    cat > docker-compose.yml << 'EOF'
    version: '3.8'
    services:
      metadefender-core:
        image: opswat/metadefender:latest
        container_name: metadefender-core
        ports:
          - "8008:8008"
          - "8009:8009"
        environment:
          - MD_LICENSE=${license_key}
          - MD_CONSOLE_LOG_LEVEL=INFO
        volumes:
          - metadefender-data:/app/data
          - metadefender-logs:/app/logs
        restart: unless-stopped
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 60s

    volumes:
      metadefender-data:
      metadefender-logs:
    EOF
  - sed -i "s/\${license_key}/${license_key}/g" /opt/opswat/docker-compose.yml
  - docker-compose up -d
  - |
    cat > /etc/systemd/system/metadefender.service << 'EOF'
    [Unit]
    Description=OPSWAT MetaDefender Core
    Requires=docker.service
    After=docker.service

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    WorkingDirectory=/opt/opswat
    ExecStart=/usr/bin/docker-compose up -d
    ExecStop=/usr/bin/docker-compose down
    TimeoutStartSec=0

    [Install]
    WantedBy=multi-user.target
    EOF
  - systemctl enable metadefender.service

write_files:
  - content: |
      #!/bin/bash
      echo "MetaDefender Core installation completed!"
      echo "Access the application at: http://$(curl -s http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress?api-version=2021-02-01 -H Metadata:true):8008"
    path: /opt/opswat/status.sh
    permissions: '0755'